services:
  db:
    image: postgres:16
    container_name: tiketera-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: tiketera
      POSTGRES_PASSWORD: tiketera
      POSTGRES_DB: tiketera
    ports:
      - "5433:5432"   # <--- CAMBIADO: host 5433 -> contenedor 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

